id: IC6E1404B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T00:07:57+00:00'
last_modified: '2022-06-09T07:57:50.943161+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28967
  title: བཟོ་གནས་སྐྲ་རྩེའི་ཆུ་ཐིགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    316B:
      image_group_id: I1PD36339
      title: Volume 1 of bzo gnas skra rtse'i chu thigs
      total_pages: 694
      order: 1
      base_file: 316B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
