id: P007955
initial_creation_type: ocr
source_metadata:
  id: bdr:W28967
  title: བཟོ་གནས་སྐྲ་རྩེའི་ཆུ་ཐིགས
  author: ''
  volumes:
    3443f2680f98432493abff93412150cb:
      image_group_id: I1PD36339
      title: ''
      volume_number: 1
      total_pages: 694
ebook_metadata:
  title: བཟོ་གནས་སྐྲ་རྩེའི་ཆུ་ཐིགས
  author: ''
  sku: P007955
  cover: cover.jpg
  layers:
  - pagination
